# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  movie_insert(
    data: {id: "11111111222233334444555555555556", genre: "aaa", imageUrl: "", title: "title"}
  )
}